### ISSUE TITLE
TypeError: Cannot read property 'stderr' of undefined

### ISSUE THREAD

**Issue by benyamindsmith** [FabrizioSandri/r-integration#5]
Hi I'm back!

I have some R code which creates a leaflet map and I want to be able to use this module for being able to produce leaflet maps with my original R code without having to rewrite the code in Javascript.

R code I have is: 

```r
library(tidyverse)
library(leaflet)
library(tidygeocoder)
library(osrm)



plot_route_Mapbox<-function(to, 
                            from,
                            how="car",
                            colour="black",
                            opacity=1,
                            weight=1,
                            radius=2,
                            label_text=c(to,from),
                            label_position="bottom",
                            provider=providers$CartoDB.PositronNoLabels,
                            font = "Lucida Console",
                            font_weight="bold",
                            font_size= "14px",
                            text_indent="15px",
                            saturation=0,
                            mapBoxTemplate= "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"){
  address_single <- tibble(singlelineaddress = c(to,from)) %>% 
    geocode(address=singlelineaddress,method = 'arcgis') %>% 
    transmute(id = singlelineaddress,
              lon=long,
              lat=lat)
  
  trip <- osrmRoute(src=address_single[1,2:3] %>% c,
                    dst=address_single[2,2:3] %>% c,
                    returnclass="sf", 
                    overview="full",
                    osrm.profile = how )
  
  m<-leaflet(trip,
             options = leafletOptions(zoomControl = FALSE,
                                      attributionControl=FALSE)) %>%
    fitBounds(lng1 = max(address_single$lon)+0.1,
              lat1 = max(address_single$lat)+0.1,
              lng2 = min(address_single$lon)-0.1,
              lat2 = min(address_single$lat)-0.1) %>%  
    addTiles(urlTemplate = mapBoxTemplate) %>% 
    addCircleMarkers(lat = address_single$lat,
                     lng = address_single$lon,
                     color = colour,
                     stroke = FALSE,
                     radius = radius,
                     fillOpacity = opacity) %>%
    addPolylines(color = colour,
                 opacity=opacity,
                 weight=weight) %>% 
    addLabelOnlyMarkers(address_single$lon,
                        address_single$lat, 
                        label =  label_text,
                        labelOptions = labelOptions(noHide = T,
                                                    direction = label_position,
                                                    textOnly = T,
                                                    style=list("font-family" = font,
                                                               "font-weight"= font_weight,
                                                               "font-size"=font_size,
                                                               "text-indent"=text_indent))) 
  
  m
}
```

and I am interested in compiling it in nodeJs with the following code. 

```js
R.callMethod(
  "Test.R",
  "plot_route_Mapbox",
   ["Toronto","Niagara Falls"],
  (RBinariesLocation = "C:\\Program Files\\R")
);
```

I get the following Terminal output: 

```
PS D:\RandJavascript> node RScriptInJavascript
D:\RandJavascript\node_modules\r-integration\src\R.js:121
            console.error(`[R: compile error] ${commandResult.stderr.stderr}`);
                                                                     ^

TypeError: Cannot read property 'stderr' of undefined
    at executeRCommand (D:\RandJavascript\node_modules\r-integration\src\R.js:121:70)
    at Object.callMethod (D:\RandJavascript\node_modules\r-integration\src\R.js:255:14)
    at Object.<anonymous> (D:\RandJavascript\RScriptInJavascript.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

Appreciate the help!

**Comment by FabrizioSandri** [comment]
@benyamindsmith good catch ! There was a typo while printing the compile error.

Update to version 1.7.0 with npm
